// REGISTRATION
  // USER USERNAME AND PASSWORD WERE ADDED TO USERS ARRAY UPON REGISTRATION ***DONE***
  // GET RID OF ABILITY TO CREATE DUPLICATED ACCOUNTS BASED ON USERNAME ***DONE***

// LOGIN
  // MAKE DYNAMIC
    // WILL SEARCH ARRAY FOR MATCHING DATA => NO MATCH = ERROR ***DONE***
  // USER CAN NOT LOG IN AGAIN WITHOUT LOGGING OUT ***DONE***
  // USER WILL BE LOGGED OUT BY CLICKING 'LOG OUT' LINK ***DONE***
  // USER WILL BE TAKEN TO PERSONAL PROFILE AFTER LOGGING IN

// UNIQUE IDENTITIES
  // UPON REGISTERING, USER WILL BE GIVEN A UNIQUE ID (1 TO 500,000) <= LOOK INTO LATER