// REGISTRATION
  // USER USERNAME AND PASSWORD WERE ADDED TO USERS ARRAY UPON REGISTRATION ***DONE***
  // GET RID OF ABILITY TO CREATE DUPLICATED ACCOUNTS BASED ON USERNAME ***DONE***
  // USER WILL BE TAKEN TO PERSONAL CREATE PROFILE PAGE AFTER REGISTERING
    // AFTER CREATING PROFILE, USER WILL BE TAKEN TO MYPROFILE PAGE
    //  REGISTRATION WILL NEED TO ADD A TOKEN ***DONE***
  // USER USERNAME IS SET TO ACTIVEUSER STATE ***DONE***

// LOGIN
  // MAKE DYNAMIC
    // WILL SEARCH ARRAY FOR MATCHING DATA => NO MATCH = ERROR ***DONE***
  // USER CAN NOT LOG IN AGAIN WITHOUT LOGGING OUT ***DONE***
  // USER WILL BE LOGGED OUT BY CLICKING 'LOG OUT' LINK ***DONE***
    // ADD WINDOW ALERT THAT USER WILL BE LOGGED OUT WHEN TRYING TO EXIT SITE??? (KIND OF ANNOYING)
  // USER WILL BE TAKEN TO PERSONAL PROFILE AFTER LOGGING IN ***DONE***
    // TEMPORARILY ADD 'WELCOME, <INSERT USERNAME>' TO MAKE SURE PROFILE IS TRULY UNIQUE ***DONE***
  // SHOW 403 ERROR MESSAGE ***DONE***
  // CHECK WHETHER OR NOT ACTIVEUSER STORE PERSISTED (localhost:5000/activeUser) ***DONE***
  // GET INFORMATION OF ACTIVEUSER SO USERNAME SHOWS ON SCREEN ***DONE***
  // USER USERNAME IS SET TO ACTIVEUSER STATE ***DONE***

// LOGOUT
  // ACTIVEUSER SHOULD BE EMPTIED ***DONE***

// UNIQUE IDENTITIES
  // UPON REGISTERING, USER WILL BE GIVEN A UNIQUE ID (1 TO 500,000) <= LOOK INTO LATER

// LOGIN/LOGOUT
  // LOGIN LINK DISAPPEARS WHEN TOKEN IS PRESENT ***DONE***
  // LOGOUT LINK DISAPPEARS WHEN TOKEN IS NOT PRESENT ***DONE***

// PAGE/FORM STRUCTURE
  // SEPARATE ALL FORMS AND PAGES *** DONE ***

// REFACTOR CODE
  // CODE WILL RELY ON REDUX TO STORE CURRENT LOGGED IN USER SO USER WILL NOT BE ABLE TO GET INTO OTHER USERS' PROFILES THROUGH URL ***DONE***
  // AS SOON AS USER IS LOGGED IN, THEIR DATA IS ADDED TO THE ACTIVEUSER ARRAY ***DONE***
// SERVER
  // CHANGE COMMENTS ***DONE***

// MY PROFILE
  // IF LINK IS CLICKED, ACTIVE USER ID IS CHECKED AND THE ID IS INSERTED INTO URL???
    // THIS DEPENDS ON HOW THE USERPROFILE ROUTE WORKS, THERE MAY BE A WAY TO REMOVE THE ID FROM THE URL